-- comments-canonique-v31.sql — RE-SYNC DOC CANONIQUE (M492/M509 lot 1) : COMMENT ON des facteurs MCDA v3.
-- POUR B : à appliquer sur DB2 (owner-safe, NON calcul, AUCUNE donnée/ligne touchée — que des métadonnées de doc).
-- Source de vérité = DB1 mcda2.base_reward_inputs (posé A159, validé M495). Idempotent (COMMENT ON écrase). Sémantique ancrée docs/gis-mcda/.
COMMENT ON TABLE mcda2.base_reward_inputs IS 'MCDA v3 (autorité A, M491/M492) : facteurs par-base consommés par le composeur (reward_base). Sémantique ANCRÉE dans docs/gis-mcda/ (notes 04 curseurs, 05 envies, 07 critères qualité, 16 récompense). f1-f5 = familles de critères qualité couche 1 (inclinées par le curseur Registre + signature archétype w_*) ; reward_top8 = aimant incontournables ; hors_foule/lat_norm = proxy foule / biais nord ; th_* = envies couche 2a ; cout_moy = prix couche 3. NB R1 : le RECALCUL exact des valeurs est v3.1 (le live v3.0 lit encore des inputs v2-dérivés) ; f6 n''apparaît PAS dans reward_base (composeur f1-f5+rtop) = colonne à trancher (scorie ou usage futur).';
COMMENT ON COLUMN mcda2.base_reward_inputs.f1 IS 'Qualité NATURE/naturalité de la base (couche 1, note 07 ; pondéré w_nat, curseur Registre pôle Nature). Libellé v3 : « Nature sauvage ». 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.f2 IS 'Qualité GRANDEUR du paysage (couche 1, note 07 ; pondéré w_gra). Libellé v3 : « Grands paysages ». 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.f3 IS 'Qualité TRANQUILLITÉ/solitude (couche 1, note 07 ; pondéré w_tra ; lié curseur Foule). Libellé v3 : « Calme et solitude ». 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.f4 IS 'Aptitude/intérêt RANDONNÉE (couche 1/envie rando ; pondéré w_ran, curseur Effort). Libellé v3 : « Randonnée ». 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.f5 IS 'Aptitude BIVOUAC/autonomie (pondéré w_biv, curseur Nuit pôle Autonomie). Libellé v3 : « Bivouac / autonomie ». 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.f6 IS 'R1/M492 : NON consommé par reward_base (composeur n''utilise que f1-f5+reward_top8). Sémantique v2 non identifiée dans docs/gis-mcda/ → à TRANCHER (scorie à droper ou 6e critère à rebrancher en v3.1). Ne pas mapper au questionnaire tant que non tranché.';
COMMENT ON COLUMN mcda2.base_reward_inputs.reward_top8 IS 'Aimant INCONTOURNABLES : Σ des 8 meilleurs V_poi atteignables depuis la base (pondéré w_inc ; envie_iconique note 05). Normalisé par rtop_max au runtime. Libellé v3 : « Incontournables à portée ».';
COMMENT ON COLUMN mcda2.base_reward_inputs.hors_foule IS 'Proxy TRANQUILLITÉ/fréquentation (note 07 : la foule = résultat, modélisée en proxy). reward_base soustrait anti_foule*(1-hors_foule). Libellé v3 : « Loin de la foule ». 0-1 (1 = paisible).';
COMMENT ON COLUMN mcda2.base_reward_inputs.lat_norm IS 'Latitude normalisée 0-1 (biais géographique NORD, curseur/param biais_nord ; cap nord). geo_pref = biais_nord*lat_norm + (1-biais_nord)*(1-lat_norm). Libellé v3 : « Position nord ».';
COMMENT ON COLUMN mcda2.base_reward_inputs.cout_moy IS 'Coût moyen indicatif de la base (couche 3 PRIX, note 16 ; critère orthogonal). reward_base soustrait SENS_PRIX*(cout_moy/COUT_REF). Coulisses uniquement (pas de score brut en surface, note 20).';
COMMENT ON COLUMN mcda2.base_reward_inputs.th_paysage IS 'Envie PAYSAGE (couche 2a, note 05 ; theme_match). Axe questionnaire candidat. 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.th_rando IS 'Envie RANDO (couche 2a, note 05 ; theme_match). Axe questionnaire candidat. 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.th_nautique IS 'Envie NAUTIQUE (couche 2a, note 05 envie_nautique kayak/croisière). Axe questionnaire DÉDIÉ recommandé. 0-1.';
COMMENT ON COLUMN mcda2.base_reward_inputs.th_culturel IS 'Envie CULTUREL (couche 2a, note 05 envie_culturel musées/villages/sites). Axe questionnaire DÉDIÉ recommandé. 0-1.';
